version: '3.1'

services:
 db:
   image: postgres
   ports:
    - 5432:5432
   environment:
    POSTGRES_PASSWORD: root
   networks:
    - postgres-compose-network     
  
 db-admin:
   image: dpage/pgadmin4
   ports:
    - 15432:80
   environment:
    PGADMIN_DEFAULT_EMAIL: "root@root.com"
    PGADMIN_DEFAULT_PASSWORD: "root"
   depends_on:
    - db
   networks:
    - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge